# Algorithm list for chain: seaice

# Optional file selector modules
l1b_file_selectors:
  - stage_3_file_finder

# List of algorithms to call in order
algorithms:
  - alg_grid_average
  - alg_output_maps
  - alg_output_ascii