[tool.poetry]
name = "clev2er"
version = "0.1.0"
description = ""
authors = ["Alan Muir <a.muir@ucl.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
