# Main configuration file for CLEV2ER chain
#  - you can use env variables in this file

project: "CLEV2ER"

# Default locations for log files
log_files:
  errors: ${CLEV2ER_BASE_DIR}/logs/errors.log
  info:   ${CLEV2ER_BASE_DIR}/logs/info.log
  debug:  ${CLEV2ER_BASE_DIR}/logs/debug.log

# Processing chain operation settings
chain:
  use_multi_processing: false
  max_processes_for_multiprocessing: 7
  # default is to skip file if an algorithm returns failure and continue
  stop_on_error: true

# Geophysical parameters
geophysical:
  earth_semi_major: 6378137.0
  eccentricity: 0.08181919078479198
  speed_light: 299792458.0

# Resource Locators
surface_type_masks:
  antarctica_bedmachine_v2_grid_mask: ${CPDATA_DIR}/RESOURCES/surface_discrimination_masks/antarctica/bedmachine_v2/BedMachineAntarctica_2020-07-15_v02.nc
  greenland_bedmachine_v3_grid_mask:  ${CPDATA_DIR}/RESOURCES/surface_discrimination_masks/greenland/bedmachine_v3/BedMachineGreenland-2017-09-20.nc
  antarctica_iceandland_dilated_10km_grid_mask:  ${CPDATA_DIR}/RESOURCES/surface_discrimination_masks/antarctica/bedmachine_v2/dilated_10km_mask.npz
  greenland_iceandland_dilated_10km_grid_mask:   ${CPDATA_DIR}/RESOURCES/surface_discrimination_masks/greenland/bedmachine_v3/dilated_10km_mask.npz

tides:
  fes2014b_base_dir: /raid6/cpdata/SATS/RA/CRY/L1B/FES2014
  cats2008a_base_dir: /raid6/cpdata/SATS/RA/CRY/L2I/SIN/CATS_tides

slope_models:
  model_file: /raid6/cpdata/RESOURCES/slope_models/cs2/CS_OPER_AUX_SLPMSL_00000000T000000_99999999T999999_0007.DBL

dem_dirs:
  antarctic_dem_1km: rema_ant_1km
  greenland_dem_1km: arcticdem_1km

