project: "CLEV2ER"

log_files:
  errors: ${CLEV2ER_BASE_DIR}/logs/errors.log
  info:   ${CLEV2ER_BASE_DIR}/logs/info.log
  debug:  ${CLEV2ER_BASE_DIR}/logs/debug.log

algorithm_lists:
  land_ice: ${CLEV2ER_BASE_DIR}/config/li_algorithms.yml
  inland_waters: ${CLEV2ER_BASE_DIR}/config/iw_algorithms.yml
