# Main configuration file for CLEV2ER chain
#  - you can use env variables in this file

# Processing chain operation settings
chain:
  use_multi_processing: false # if false l1b files are processed sequentially
  max_processes_for_multiprocessing: 12 # if MP enabled: process a maximum of N input files in parallel
                                       # before processing the next N files
  number_of_files_per_process: 1 # if MP enabled, each process is passed n files to process
  use_shared_memory: false # for multi-processing, optionally allocate SharedMemory buffers
                           # on Algorithm initialization for resources such as DEM
                           # arrays. This can greatly reduce overall memory usage for MP
                           # May not work on all operating systems, and has additional
                           # risks if not unlinked/closed correctly from each process
  stop_on_error: false # if false: skip file on error, and continue processing next one
                       # if true: stop all processing after an error

