# Algorithm list for chain: seaice

# Optional file selector modules
l1b_file_selectors:
  - stage_2_file_finder

# List of algorithms to call in order
algorithms:
  - alg_add_mss
  - alg_add_si_type
  - alg_dynamic_snow_load
  - alg_sla_calculations
  - alg_fbd_calculations
  - alg_thk_calculations
  - alg_floe_chord_length
  - alg_merge_months
