# Algorithm list for chain: seaice

# Optional file selector modules
l1b_file_selectors:
#  - your_finder
#  - your_finder2
#  - ...

# List of algorithms to call in order
algorithms:
  - alg_add_mss
  - alg_add_si_type
  - alg_sla_calculations
  - alg_fbd_calculations
  - alg_warren_snow_means
  - alg_thk_calculations
  - alg_grid_for_volume
