# CPOM sea ice chain settings

# Set breakpoint file directory
breakpoint_files:
  default_dir: ${HOME}/sea_ice_processor/bp_files
  
# Default locations for log files
log_files:
  append_year_month_to_logname: true  # if chain is run for specific month and year, use <logtype>_MMYYYY.log
                                      # or <logtype>_YYYY.log (if only year specified) 
  errors: ${SI_LOG_DIR}/errors.log    # or errors_MMYYYY.log
  info:   ${SI_LOG_DIR}/info.log
  debug:  ${SI_LOG_DIR}/debug.log

# CS2 instrument parameters
instrument:
  num_range_bins_lrm: 128
  # etc

# Geophysical parameters
geophysical:
  earth_semi_major: 6378137.0
  eccentricity: 0.08181919078479198
  speed_light_vacuum: 299792458.0
  speed_light_snow:   240000000.0 #2.4e8

# Algorithm configuration settings

shared: # Shared config parameters for multiple algorithms to use
  min_latitude: 30.00 # minimum latitude in degs N
  max_latitude: 90.00 # maximum latitude in deg N
  min_longitude: 0.00 # minimum longitude in degs E
  max_longitude: 360.00 # maximum longitude in deg E
  output_projection: epsg:3413 # projection used within chain
  aux_file_path: ${HOME}/sea_ice_processor/aux_files
  nlons: 720
  nlats: 500

alg_vol_calculations:
  ninmin: 5

alg_vol_fill_nn:
  working_projection: epsg:3413

alg_add_ice_extent:
  conc_threshold: 15.0
  input_projection: epsg:4326
  
alg_add_cell_area:
  input_projection: epsg:4326

alg_add_ocean_frac:
  input_projection: epsg:4326

alg_add_region_mask:
  mask_number: 1

alg_output_ascii:
  output_directory: ${HOME}/sea_ice_processor/ascii_outputs